# -*- coding: utf-8 -*-
"""complementing_a_strand_of_dna.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1txn2R6CFMUQ2T0-jfSkhoFRsEVyhMuqq
"""

#Complementing a Strand of DNA

seq = 'AAAACCCGGT'
seq = seq.replace("A","t",).replace("T", "a").replace("G", "c").replace("C","g").upper()

novaseq = seq[::-1]
print (novaseq)