# -*- coding: utf-8 -*-
"""counting_dna_nucleotides.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/107vI30YltG_tbuZCr87-fP6fWSVJYDme
"""

#Counting DNA Nucleotides

text = 'AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC'
print('{0} {1} {2} {3}'.format(text.count('A'),text.count('C'),text.count('G'),text.count('T')))