# -*- coding: utf-8 -*-
"""transcribing_dna_rna.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P3fegmX_oMt_TD7_Qs2t3Axise0kztAy
"""

#Transcribing DNA into RNA

seq = 'GATGGAACTTGACTACGTAAATT'
novaseq = seq.replace("T", "U")
print(novaseq)